spring:
  datasource:
    url: ${DB_URL:jdbc:h2:file:./data/ugeoverflowdb}
    driverClassName: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
  h2:
    console:
      enabled: ${DB_CONSOLE_ENABLED:false}

ugeoverflow:
  admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin}