spring:
  datasource:
    url: ${DB_URL:jdbc:h2:file:./data/ugeoverflowdb}
    driverClassName: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
    open-in-view: false
  h2:
    console:
      enabled: ${DB_CONSOLE_ENABLED:false}
  mvc:
    hiddenmethod:
      filter:
        enabled: true

ugeoverflow:
  admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin}
  session:
    purge-rate: ${SESSION_PURGE_RATE:300000}
    access-token-lifetime: ${ACCESS_TOKEN_LIFETIME:3600000}
    refresh-token-lifetime: ${REFRESH_TOKEN_LIFETIME:2592000000}
  answer-algorithm:
    circle-max-depth: ${CIRCLE_MAX_DEPTH:3} # Max depth of the following circles used for final note calculation
